USE MASTER;
GO
ALTER DATABASE BookAppDB SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
Drop Database BookAppDB;
GO

Create Database BookAppDB;
GO

USE BookAppDB;
GO
--
-- Publisher table has a list of all book publishers
--
Create Table Publisher
(
	Publisher_ID int IDENTITY(1,1) NOT NULL, --PK(1/1)
	Publisher_Name nvarchar(255) NOT NULL,
	Constraint PK_Publisher_ID Primary Key(Publisher_ID)
);
GO

Create Table Genre
(
	Genre_ID int IDENTITY(1,1) NOT NULL, --PK(1/1)
	Genre_Name nvarchar(255) NOT NULL,
	Constraint PK_GENRE_ID Primary Key(Genre_ID)
);
GO

Create Table Author
(
	Author_ID int IDENTITY(1,1) NOT NULL , --PK(1/1)
	Author_First_Name nvarchar(255) NOT NULL,
	Author_Middle_Name nvarchar(255),
	Author_Last_Name nvarchar(255) NOT NULL,
	Constraint Author_ID_PK Primary Key(Author_ID)
);
GO

Create Table Book
(
--CHANGE TO NOT NULL.
	Book_ISBN nvarchar(13) NOT NULL,--PK(1/1)
	Book_Title nvarchar(255) NOT NULL ,
	Book_Genre int NOT NULL,  --FK(1/1)
	Book_Year int NOT NULL,
	Book_Quantity int NOT NULL DEFAULT 1,
	Constraint Book_ISBN_PK PRIMARY KEY(Book_ISBN),
	Constraint Book_Genre_FK FOREIGN KEY(Book_Genre) REFERENCES Genre(Genre_ID)

);
GO

--Book_Authors
Create Table Book_Authors
(
	Book_ISBN nvarchar(13) NOT NULL,--FK(1/2)
	Author_ID int NOT NULL--FK(2/2)
	CONSTRAINT BOOK_FK FOREIGN KEY(BOOK_ISBN) REFERENCES Book(Book_ISBN),
	CONSTRAINT Author_FK FOREIGN KEY(Author_ID) REFERENCES Author(Author_ID)
);

-------------------------------------------------------------------------------------------------------------------- 
--
--  End of BookAppDB Database Definitions
--
-------------------------------------------------------------------------------------------------------------------- 

INSERT INTO Publisher
(Publisher_Name)
VALUES
('Riverhead'),
('Scribner'),
('Vintage'),
('St. Martin"s'),
('Penguin Group'),
('Washington Square'),
('Andrews McMeel'),
('Bantam'),
('Berkley'),
('Ballantine'),
('Scout'),
('Penguin Press'),
('Knopf Doubleday Publishing'),
('Houghton Mifflin Harcourt'),
('Doubleday'),
('Grand Central'),
('Broadway'),
('Dell'),
('Forge Books'),
('Entangled Publishing'),
('Harper'),
('Morrow'),
('Delacorte'),
('Windblown Media'),
('Sarah Crichton/Farrar, Straus & Giroux'),
('Delacorte Press'),
('Darcie Chan'),
('Ecco/HarperCollins'),
('Little, Brown'),
('Putnam'),
('Knopf'),
('Little, Brown & Company'),
('Knopf Doubleday'),
('Viking'),
('Flatiron'),
('Tracey Garvis-Graves'),
('Algonquin'),
('Random House'),
('Picador'),
('Random House Publishing'),
('Rachel Van Dyken'),
('Colleen Hoover'),
('Atria Books'),
('Crown'),
('Simon & Schuster'),
('Norton'),
('HarperCollins'),
('Harlequin'),
('Dutton'),
('Emily Bestler/Atria'),
('Mulholland/Little, Brown'),
('Pamela Dorman/Viking'),
('Morrow/HarperCollins'),
('Harper/HarperCollins'),
('Marian Wood/Putnam'),
('Barbara Freethy'),
('Witness Impulse/HarperCollins'),
('Grand Central Publishing'),
('Legacy'),
('Atria/Emily Bestler'),
('Pocket Books'),
('St. Martin"s Griffin'),
('Penelope Ward'),
('Soho Press'),
('Laree Bailey'),
('Harlequin Mira'),
('Jasinda Wilder'),
('Addison Moore'),
('Jessica Sorensen'),
('Mira'),
('Penguin'),
('Tor'),
('Zebra'),
('Gallery Books'),
('EverAfter Romance'),
('Atria'),
('Roc'),
('Helen Cooper'),
('Gail McHugh'),
('Hard Case Crime'),
('Broad Reach Publishing'),
('Tor/Tom Doherty Associates'),
('Abbi Glines'),
('Elisabeth Naughton'),
('Minotaur'),
('HQN'),
('St. Martinâ€™s'),
('Tijan'),
('Lauren Blakely'),
('Anchor'),
('Touchstone'),
('Lucasbooks'),
('Del Rey'),
('Farrar, Straus & Giroux'),
('CreateSpace'),
('Metal Blonde'),
('Melanie Marchande'),
('Tor/Tom Doherty'),
('J.C. Reed'),
('Birch Paper Press'),
('Georgia Cates'),
('Courtney Cole'),
('Raine Miller'),
('Berkley Books'),
('St. Martinâ€™s Press'),
('P. J. Alderman'),
('Gallery'),
('C. Scott Publishing'),
('Red Dress Press'),
('Susan Stoker'),
('Ace'),
('Oak Press'),
('MIRA'),
('C. Scott'),
('Avon'),
('Red Dress'),
('Atlantic Monthly'),
('Kensington'),
('BAAE'),
('Waterhouse'),
('Dial'),
('Tyndale House'),
('Vi Keeland'),
('Heidi McLaughlin'),
('Orbit'),
('Pantheon'),
('Kristen Ashley'),
('Howard Books'),
('Flatiron Books'),
('Atria/Keywords'),
('BookShots'),
('Random House Publishing Group'),
('Howard'),
('Cemetery Dance'),
('Penelope Sky'),
('Ampersand'),
('ROC'),
('Valkyrie'),
('Waterhouse Press'),
('Jove'),
('Golden Unicorn Enterprises'),
('genreCrave'),
('Romig Works'),
('Henry Holt'),
('Signet'),
('Avon Impulse'),
('DLZ Entertainment'),
('Emma Chase'),
('Elle Kennedy'),
('Avon/HarperCollins'),
('Nan A. Talese/Doubleday'),
('Jamie McGuire'),
('Blue Bolt'),
('Witness Impulse'),
('New American Library'),
('Kendall Ryan'),
('Aurora Rose Reynolds'),
('Denise Grover Swank'),
('St. Martin"s Press'),
('Valkyrie Press'),
('InterMix'),
('Loveswept'),
('Crown Archetype'),
('Forever'),
('Harper Perennial/HarperCollins'),
('Kingswell'),
('Carina'),
('JMC Creations'),
('HTJB'),
('Dutton/Penguin Publishing Group'),
('Zebra/Mulholland'),
('NAL'),
('Sydney Landon'),
('Hoover Ink'),
('Rerum Industries'),
('Julia Kent'),
('Pepper Winters'),
('Holt'),
('Forever/Grand Central'),
('Pocket Star'),
('Science Future Press'),
('Harper Sloan'),
('Zebra/Kensington'),
('Deborah Bladon'),
('DAW'),
('Bella Andre'),
('Ellora"s Cave'),
('Harper Voyager'),
('Loveswept/Random House'),
('Laurelin Paige'),
('J. Daniels'),
('Various publishers'),
('Meredith Wild'),
('H. M. Ward'),
('Whitney Williams'),
('Mia Sheridan'),
('Golden Unicorn'),
('Smashwords'),
('SOS Ladies'),
('Berkley Sensation'),
('Carina Press'),
('Harper Perennial'),
('JKB'),
('Debbie Macomber Books'),
('HarperVoyager'),
('H. M. Ward Press'),
('Vintage Crime/Black Lizard'),
('Copper Key Media'),
('Laurens Publishing'),
('Sprigleaf'),
('Sandi Lynn'),
('Gossamer'),
('Knopf/McSweeney‰Ûªs'),
('Hyperion'),
('Jen McLaughlin'),
('Bloomsbury'),
('Maya Cross'),
('Ecila Media'),
('Novelty Books'),
('Amy Harmon'),
('Omnific'),
('Sourcebooks Landmark'),
('Sourcebooks'),
('The Indie Voice'),
('Katie Ashley'),
('HarperCollins Publishers'),
('Tyndale House Publishers'),
('Marie Force'),
('Shanora Williams'),
('Hyperion Press'),
('Kensington Publishing'),
('Zondervan'),
('Henry Holt & Company'),
('Elloraâ€™s Cave Publishing'),
('Crown Publishing'),
('Elloraâ€™s Cave'),
('Tom Doherty Associates'),
('Center Street'),
('Threshold Editions'),
('Paragon Press'),
('Thorndike'),
('Doherty'),
('Dial Press'),
('Crown/Archetype'),
('Ilona Andrews'),
('Plain Jane'),
('Rutherford'),
('Baen Books'),
('KT Publishing'),
('Flip City Media'),
('CP Publishing'),
('Fine Line'),
('Thomas Nelson'),
('Europa Editions'),
('Ballatine'),
('ePublishing Works!'),
('Mariner'),
('Silhouette'),
('Open Road Media'),
('DGS'),
('Forge'),
('Pitch73'),
('Story Ink'),
('Evil Eye Concepts'),
('Amy Einhorn/Putnam'),
('JA / AG Publishing'),
('7th House'),
('J. S. Cooper'),
('Helena Hunting'),
('ERH Press'),
('Spiegel & Grau'),
('Liliana Hart'),
('Pocket'),
('Knopf Doubleday Publishing Group'),
('Vision'),
('J.S. Cooper'),
('WGW'),
('Latin Goddess Press'),
('Lisa Renee Jones'),
('Kelley R. Martin'),
('Plume'),
('Victoria Ashley'),
('Angela Graham'),
('Uncommonly Romantic Books'),
('Violet Duke'),
('Harlequin HQN'),
('S.L. Jennings'),
('Stacy Borel'),
('J.B. Salsbury'),
('Black Oak Books'),
('Atlantic Monthly Press'),
('Tyndale'),
('Excessica'),
('Tawny Weber'),
('Steel Magnolia Press'),
('Entangled: Brazen'),
('Laree Bailey Press'),
('Kelly Elliott'),
('HTJB, Inc.'),
('Nicole Edwards'),
('Algonquin Books'),
('William Morrow Impulse'),
('Kathleen Brooks'),
('Indie Six'),
('Hugh Howey'),
('Seth Clarke'),
('Spencer Hill Contemporary'),
('Reagan Arthur/Little, Brown'),
('Cassia Leo'),
('M. Leighton'),
('Katy Evans'),
('Sapphire Star Publishing'),
('Revell'),
('FaithWords'),
('Raine Miller Romance'),
('Samhain Publishing'),
('Laurann Dohner'),
('Cora Carmack'),
('S.H. Kolee'),
('Rerum Publishing House'),
('Catherine Bybee'),
('Chris Culver'),
('Wizards of the Coast'),
('Tom Doherty'),
('Bethany House'),
('Michael Prescott'),
('Courtney Milan'),
('Recorded Books'),
('Penwyck')
;
GO
SELECT * FROM  Publisher
        Order by Publisher_ID
;
GO
INSERT INTO Genre
(Genre_Name)
VALUES
('Classic'),
('Comics/graphic'),
('Contemporary'),
('Crime/detective'),
('Fable'),
('Fairy'),
('Fan'),
('Fantasy'),
('Folktale'),
('Historical'),
('Horror'),
('Humor'),
('Legend'),
('Magical'),
('Meta'),
('Mystery'),
('Mythology'),
('Mythopoeia'),
('Picture'),
('Manga'),
('Light Novel'),
('Realistic'),
('Romance'),
('Science'),
('Short'),
('Suspense/thriller'),
('Swashbuckler'),
('Tall'),
('Theological'),
('Western'),
('Narrative'),
('Biography'),
('Essay'),
('Journalism'),
('Lab'),
('Memoir'),
('Narrative'),
('Reference'),
('Self-help'),
('Speech'),
('Textbook')
;
GO
SELECT * FROM  Genre
        Order by Genre_ID
;
GO
INSERT INTO Author
(Author_First_Name,Author_Middle_Name,Author_Last_Name)
VALUES
('Paula ','null','Hawkins'),
('Anthony ','null','Doerr'),
('E ','L ','James'),
('Kristin ','null','Hannah'),
('Kathryn ','null','Stockett'),
('Fredrik ','null','Backman'),
('Rupi ','null','Kaur'),
('George ','R ','Martin'),
('Liane ','null','Moriarty'),
('Lisa ','null','Wingate'),
('Ruth ','null','Ware'),
('Celeste ','null','Ng'),
('Stieg ','null','Larsson'),
('Margaret ','null','Atwood'),
('John ','null','Grisham'),
('Nicholas ','null','Sparks'),
('Ernest ','null','Cline'),
('Diana ','null','Gabaldon'),
('Sylvia ','null','Day'),
('Dan ','null','Brown'),
('Martha ','Hall ','Kelly'),
('Stephen ','null','King'),
('W ','Bruce ','Cameron'),
('Jennifer ','null','Probst'),
('Colson ','null','Whitehead'),
('Jodi ','null','Picoult'),
('Harper ','null','Lee'),
('AJ ','null','Finn'),
('David ','null','Baldacci'),
('Lee ','null','Child'),
('William ','P ','Young'),
('Matthew ','null','Quick'),
('William ','null','Landay'),
('Darcie ','null','Chan'),
('Yann ','null','Martel'),
('Nora ','null','Roberts'),
('Cynthia ','DAprix','Sweeney'),
('James ','null','Patterson'),
('David ','null','Lagercrantz'),
('EL ','null','James'),
('Ken ','null','Follett'),
('Tracey ','null','Garvis-Graves'),
('James ','Patterson ','Patterson'),
('Michael ','null','Ledwidge'),
('Greer ','Hendricks ','Hendricks'),
('Sarah ','null','Pekkanen'),
('Tayari ','null','Jones'),
('Janet ','null','Evanovich'),
('Emma ','null','Cline'),
('Michael ','null','Punke'),
('Max ','null','Brooks'),
('Michael ','null','Connelly'),
('David ','null','Ellis'),
('Maxine ','null','Paetro'),
('Rachel ','Van ','Dyken'),
('Maeve ','null','Binchy'),
('Colleen ','null','Hoover'),
('Vince ','null','Flynn'),
('Marshall ','null','Karp'),
('John ','null','Sandford'),
('Jason ','null','Matthews'),
('Andy ','null','Weir'),
('Nelson ','null','DeMille'),
('Elin ','null','Hilderbrand'),
('Neil ','null','Gaiman'),
('Paulo ','null','Coelho'),
('Harlan ','null','Coben'),
('Vince ','Flynn ','Flynn'),
('Kyle ','null','Mills'),
('Brad ','null','Thor'),
('Daniel ','null','Silva'),
('Robert ','null','Galbraith'),
('Stephenie ','null','Meyer'),
('Mark ','null','Sullivan'),
('Sue ','null','Grafton'),
('Charlaine ','null','Harris'),
('Danielle ','null','Steel'),
('Jojo ','null','Moyes'),
('Stephen ','King ','King'),
('Owen ','null','King'),
('Howard ','null','Roughan'),
('Candice ','null','Fox'),
('Elizabeth ','null','Strout'),
('Karin ','null','Slaughter'),
('Mitch ','null','Albom'),
('Patricia ','null','Cornwell'),
('Debbie ','null','Macomber'),
('Sandra ','null','Brown'),
('Barbara ','null','Freethy'),
('Brian ','null','McGilloway'),
('Graeme ','null','Simsion'),
('Seth ','null','Grahame-Smith'),
('CJ ','null','Lyons'),
('Mary ','Higgins ','Clark'),
('Jean ','M ','Auel'),
('Lisa ','null','Gardner'),
('Brad ','null','Meltzer'),
('Marc ','null','Cameron'),
('J ','D ','Robb'),
('Michael ','null','Crichton'),
('Mary ','Kay ','Andrews'),
('Paula ','null','McLain'),
('Mark ','null','Greaney'),
('Penelope ','null','Ward'),
('Jan ','null','Karon'),
('Michael ','null','White'),
('Deborah ','null','Harkness'),
('Jonathan ','null','Kellerman'),
('Lene ','null','Kaaberbol'),
('H ','M ','Ward'),
('Ron ','null','Carr'),
('Jasinda ','null','Wilder'),
('JA ','null','Redmerski'),
('Maya ','null','Banks'),
('Addison ','null','Moore'),
('Jessica ','null','Sorensen'),
('Sophie ','null','Kinsella'),
('J ','A ','Jance'),
('Neil ','null','McMahon'),
('Tom ','Clancy ','Clancy'),
('Grant ','null','Blackwood'),
('Shari ','null','Lapena'),
('Lisa ','null','Scottoline'),
('JD ','null','Robb'),
('Brandon ','null','Sanderson'),
('Jo ','null','Nesbo'),
('Jennifer ','null','Egan'),
('James ','O ','Born'),
('John ','le ','CarrÃ©'),
('Richard ','null','DiLallo'),
('Clive ','Cussler ','Cussler'),
('Graham ','null','Brown'),
('Janet ','Evanovich ','Evanovich'),
('Phoef ','null','Sutton'),
('Greg ','null','Iles'),
('Lisa ','null','Jackson'),
('J ','P ','Delaney'),
('Kathryn ','null','Fox'),
('Tana ','null','French'),
('Catherine ','null','Coulter'),
('Vi ','Keeland ','Keeland'),
('C ','J ','Box'),
('Justin ','null','Scott'),
('Dean ','null','Koontz'),
('Jennifer ','null','Weiner'),
('Jim ','null','Butcher'),
('Lee ','null','Goldberg'),
('J ','S ','Cooper'),
('Helen ','null','Cooper'),
('Joyce ','null','Maynard'),
('Amy ','null','Tan'),
('Gail ','null','McHugh'),
('Hugh ','null','Howey'),
('Robert ','Jordan ','Jordan'),
('Kyra ','null','Davis'),
('Susan ','null','Mallery'),
('Abbi ','null','Glines'),
('Elisabeth ','null','Naughton'),
('Stuart ','null','Woods'),
('Dorothea ','Benton ','Frank'),
('Lisa ','Jackson ','Jackson'),
('Nancy ','null','Bush'),
('CJ ','null','Box'),
('Christine ','null','Feehan'),
('Douglas ','Preston ','Preston'),
('Lincoln ','null','Child'),
('Boyd ','null','Morrison'),
('Mary ','Higgins ','Clark'),
('Alafair ','null','Burke'),
('Tom ','null','Hanks'),
('Louise ','null','Penny'),
('Mike ','null','Maden'),
('Linda ','Lael ','Miller'),
('George ','null','Saunders'),
('B ','A ','Paris'),
('Tess ','null','Gerritsen'),
('Max ','null','DiLallo'),
('Justin ','null','Cronin'),
('Lauren ','null','Blakely'),
('Richard ','null','Russo'),
('Steve ','null','Berry'),
('Jeffery ','null','Deaver'),
('Alan ','Dean ','Foster'),
('Mary ','null','Kubica'),
('Alessandra ','null','Torre'),
('Chuck ','null','Wendig'),
('Jonathan ','null','Franzen'),
('Jamie ','null','McGuire'),
('Karina ','null','Halle'),
('Melanie ','null','Marchande'),
('Anne ','null','Rice'),
('Clive ','null','Cussler'),
('Haruki ','null','Murakami'),
('Hazel ','null','Gaynor'),
('Jeffrey ','null','Archer'),
('Diane ','Mott ','Davidson'),
('JC ','null','Reed'),
('Ryan ','null','Winfield'),
('Georgia ','null','Cates'),
('Kathy ','null','Reichs'),
('J ','R ','Ward'),
('Courtney ','null','Cole'),
('James ','null','Rollins'),
('Raine ','null','Miller'),
('Jill ','null','Shalvis'),
('Gina ','L ','Maxwell'),
('P ','J ','Alderman'),
('S ','J ','Watson'),
('Mary ','Alice ','Monroe'),
('Penelope ','Ward ','Ward'),
('Vi ','null','Keeland'),
('Meghan ','null','March'),
('Rees ','null','Jones'),
('Amanda ','null','Quick'),
('Michael ','null','Ondaatje'),
('Susan ','null','Stoker'),
('Mary ','null','Balogh'),
('Faith ','null','Hunter'),
('Aimee ','null','Molloy'),
('Ace ','null','Atkins'),
('Iris ','null','Johansen'),
('Bella ','Andre ','Andre'),
('Jennifer ','null','Skully'),
('Kevin ','null','Kwan'),
('Christopher ','null','Moore'),
('Lisa ','null','Jewell'),
('JR ','null','Ward'),
('Catherine ','Coulter ','Coulter'),
('JT ','null','Ellison'),
('Madeline ','null','Miller'),
('Anne ','null','Hillerman'),
('Meg ','null','Wolitzer'),
('Kevin ','null','Hearne'),
('Jacqueline ','null','Winspear'),
('Lynsay ','null','Sands'),
('Elizabeth ','null','George'),
('Donna ','null','Leon'),
('Chris ','null','Bohjalian'),
('Randy ','Wayne ','White'),
('Patricia ','null','Briggs'),
('Jason ','null','Fry'),
('Linda ','null','Howard'),
('Karen ','Marie ','Moning'),
('Lisa ','null','Kleypas'),
('Marie ','null','Force'),
('Joanne ','null','Fluke'),
('Corinne ','null','Michaels'),
('Helen ','null','Hardt'),
('Alex ','null','Berenson'),
('Francine ','null','Rivers'),
('Kat ','null','Martin'),
('Alan ','null','Bradley'),
('Karen ','null','Cleveland'),
('Pierce ','null','Brown'),
('Heidi ','null','McLaughlin'),
('Chloe ','null','Benjamin'),
('Brad ','null','Taylor'),
('James ','Lee ','Burke'),
('Jayne ','Ann ','Krentz'),
('Jesmyn ','null','Ward'),
('Robert ','null','Crais'),
('Kate ','null','Quinn'),
('James ','S ','Corey'),
('Ashwin ','null','Sanghi'),
('Alexander ','McCall ','Smith'),
('Richard ','Paul ','Evans'),
('Kristen ','null','Ashley'),
('Karen ','null','Kingsbury'),
('Eloisa ','null','James'),
('Mark ','null','Frost'),
('Diana ','null','Palmer'),
('Alice ','null','Hoffman'),
('Bella ','null','Andre'),
('RaeAnne ','null','Thayne'),
('Nalini ','null','Singh'),
('Heather ','null','Graham'),
('Gabbie ','null','Hanna'),
('Robin ','null','Burcell'),
('Reed ','Farrel ','Coleman'),
('Craig ','null','Johnson'),
('Gabriel ','null','Tallent'),
('Tessa ','null','Dare'),
('N ','K ','Jemisin'),
('Gabrielle ','null','Zevin'),
('Stuart ','Woods ','Woods'),
('Parnell ','null','Hall'),
('Philippa ','null','Gregory'),
('Jonathan ','Kellerman ','Kellerman'),
('Jesse ','null','Kellerman'),
('Ilona ','null','Andrews'),
('Nancy ','Bush ','Bush'),
('Rosalind ','null','Noonan'),
('Iris ','Johansen ','Johansen'),
('Roy ','null','Johansen'),
('Julie ','null','Garwood'),
('Fern ','null','Michaels'),
('ï»¿Imbolo ','null','Mbue'),
('Sarah ','null','MacLean'),
('Adriana ','null','Trigiani'),
('Don ','null','Winslow'),
('Julia ','null','Quinn'),
('Richard ','null','Chizmar'),
('Scott ','null','Turow'),
('Penelope ','null','Sky'),
('Robin ','null','Hobb'),
('Dennis ','null','Lehane'),
('Jassy ','null','Mackenzie'),
('Kresley ','null','Cole'),
('Anita ','null','Shreve'),
('Timothy ','null','Zahn'),
('Kristen ','null','Pro'),
('J ','T ','Ellison'),
('Joel ','C ','Rosenberg'),
('Anne ','null','Bishop'),
('Allison ','null','Brennan'),
('Jeaniene ','null','Frost'),
('Faye ','null','Kellerman'),
('Pam ','null','Jenoff'),
('J ','S ','Scott'),
('Gwynn ','White ','White'),
('various ','null','authors'),
('Aleatha ','null','Romig'),
('Karen ','null','White'),
('Catherine ','null','Anderson'),
('Ian ','null','McGuire'),
('Bernard ','null','Cornwell'),
('Fannie ','null','Flagg'),
('James ','null','Luceno'),
('David ','null','Weber'),
('Jeffrey ','J ','Keyes'),
('Brent ','null','Weeks'),
('Lexi ','null','Blake'),
('Emma ','null','Chase'),
('Laurell ','K ','Hamilton'),
('WEB ','Griffin ','Griffin'),
('William ','E ','Butterworth'),
('Elle ','null','Kennedy'),
('Ian ','null','McEwan'),
('Clare ','null','Mackintosh'),
('Jonathan ','Safran ','Foer'),
('Susan ','Elizabeth ','Phillips'),
('Jasmine ','Walt ','Walt'),
('Rebecca ','null','Hamilton'),
('Sherrilyn ','null','Kenyon'),
('Jayne ','null','Castle'),
('Linda ','null','Fairstein'),
('Linda ','null','Castillo'),
('Kendall ','null','Ryan'),
('Emily ','null','Raymond'),
('Brad ','Meltzer ','Meltzer'),
('Tod ','null','Goldberg'),
('Alan ','null','Furst'),
('Aurora ','Rose ','Reynolds'),
('Laura ','null','Griffin'),
('Denise ','Grover ','Swank'),
('Jane ','null','Green'),
('Claudia ','null','Gray'),
('Kylie ','null','Scott'),
('Gilly ','null','Macmillan'),
('Bryan ','null','Reardon'),
('Helen ','null','Simonson'),
('Sawyer ','null','Bennett'),
('Kathleen ','null','Grissom'),
('Colm ','null','Toibin'),
('Lori ','null','Foster'),
('P ','D ','James'),
('Christina ','null','Lauren'),
('Tami ','null','Hoag'),
('Jay ','null','Crownover'),
('Kristan ','null','Higgins'),
('Kim ','van ','Alkemade'),
('Joanna ','null','Wylde'),
('John ','null','Irving'),
('Gillian ','null','Flynn'),
('Kate ','null','Morton'),
('Joseph ','Fink ','Fink'),
('Jeffrey ','null','Cranor'),
('Garth ','Risk ','Hallberg'),
('John ','Sandford ','Sandford'),
('J ','D ','Robb'),
('Richard ','null','Castle'),
('Meredith ','null','Wild'),
('Russell ','null','Blake'),
('JS ','null','Cooper'),
('Maggie ','Shayne ','Shayne'),
('Lori ','null','Herter'),
('W ','E ','Griffin'),
('William ','E ','IV'),
('Jude ','null','Deveraux'),
('Joseph ','null','Finder'),
('K ','null','Bromberg'),
('Stephanie ','null','Laurens'),
('Sydney ','null','Landon'),
('Colleen ','Hoover ','Hoover'),
('Tarryn ','null','Fisher'),
('John ','null','Lescroart'),
('R ','L ','Mathewson'),
('Penelope ','null','Douglas'),
('Kay ','null','Hooper'),
('Peter ','V ','Brett'),
('Julia ','null','Kent'),
('Gregg ','null','Olsen'),
('Katy ','null','Evans'),
('Pepper ','null','Winters'),
('Kazuo ','null','Ishiguro'),
('Richard ','Price ','Brandt'),
('Jodi ','Ellen ','Malpas'),
('J ','A ','Huss'),
('Sarah ','Addison ','Allen'),
('Rob ','Thomas ','Thomas'),
('Jennifer ','null','Graham'),
('Harper ','null','Sloan'),
('Sherryl ','null','Woods'),
('Phil ','null','Klay'),
('Gena ','null','Showalter'),
('Deborah ','null','Bladon'),
('Patrick ','null','Rothfuss'),
('Laurann ','null','Dohner'),
('Kim ','null','Harrison'),
('David ','null','Mitchell'),
('Matthew ','null','Thomas'),
('Lev ','null','Grossman'),
('Terry ','null','Goodkind'),
('Tracy ','null','Wolff'),
('Laurelin ','null','Paige'),
('Anne ','Rivers ','Siddons'),
('J ','null','Daniels'),
('Cathryn ','Fox ','Fox'),
('Alice ','null','Clayton'),
('Lisa ','null','See'),
('Stephen ','null','Hunter'),
('Whitney ','null','G'),
('James ','Rollins ','Rollins'),
('Mia ','null','Sheridan'),
('JS ','null','Scott'),
('M ','Malone ','Malone'),
('Barbara ','Freethy ','Freethy'),
('Delilah ','null','Devlin'),
('Sharon ','Hamilton ','Hamilton'),
('Kimberly ','null','McCreight'),
('Wiley ','null','Cash'),
('Jennifer ','null','Ashley'),
('Jess ','null','Walter'),
('Terry ','null','Pratchett'),
('Olen ','null','Steinhauer'),
('Jean ','Hanff ','Korelitz'),
('Tara ','null','Conklin'),
('KM ','null','Scott'),
('J ','null','Lynn'),
('Lora ','null','Leigh'),
('Kathleen ','null','Brooks'),
('VC ','null','Andrews'),
('Helene ','null','Wecker'),
('Annette ','Blair ','Blair'),
('J ','null','Kenner'),
('Sylvain ','null','Reynard'),
('Sandi ','null','Lynn'),
('Melody ','null','Anne'),
('J ','A ','Redmerski'),
('Dave ','null','Eggers'),
('Tara ','Sue ','Me'),
('Jen ','null','McLaughlin'),
('Thomas ','null','Pynchon'),
('Michael ','null','Brandman'),
('HM ','null','Ward'),
('M ','null','Leighton'),
('Marisha ','null','Pessl'),
('Samantha ','null','Shannon'),
('Maya ','null','Cross'),
('C ',' ','Box'),
('Shayla ','Black ','Black'),
('Tanya ','Anne ','Cros'),
('Danelle ','null','Harmon'),
('Lauren ','Royal ','Royal'),
('Cynthia ','null','Wright'),
('Amy ','null','Harmon'),
('Judith ','Merkle ','Riley'),
('John ','le ','Carre'),
('Samantha ','null','Young'),
('Ann ','null','Patchett'),
('Edward ','null','Rutherfurd'),
('Michael ','null','Robotham'),
('Susanna ','null','Kearsley'),
('Jana ','DeLeon ','DeLeon'),
('Katie ','null','Ashley'),
('Terry ','null','Brooks'),
('S ','C ','Stephens'),
('Shanora ','null','Williams'),
('Jackie ','null','Collins'),
('Dorien ','null','Kelly'),
('Sarah ','null','Jio'),
('Tom ','null','Wolfe'),
('H ','P ','Mallory'),
('Beth ','null','Kery'),
('Michael ','null','Chabon'),
('Tina ','null','Reber'),
('Junot ','null','DÃ­az'),
('Junot ','null','DÌ_az'),
('Laura ','null','Moriarty'),
('Rachel ','null','Gibson'),
('Hilary ','null','Mantel'),
('Troy ','null','Denning'),
('Chris ','null','Pavone'),
('Lara ','null','Adrian'),
('Sabrina ','null','Jeffries'),
('George ','null','Pelecanos'),
('Jennifer ','null','McMahon'),
('Nevada ','null','Barr'),
('Garth ','null','Stein'),
('Drew ','null','Karpyshyn'),
('Ted ','null','Dekker'),
('Glenn ','null','Beck'),
('Guillermo ','del ','Toro'),
('Chuck ','null','Hogan'),
('Douglas ','E ','Richards'),
('Julian ','null','Barnes'),
('James ','null','Wesley'),
('Neal ','null','Stephenson'),
('Johanna ','null','Lindsey'),
('Ann ','null','Brashares'),
('Aaron ','null','Allston'),
('Henning ','null','Mankell'),
('Tea ','null','Obreht'),
('Jamie ','null','Ford'),
('JA ','null','Jance'),
('Mary ','Ann ','Shaffer'),
('Annie ','null','Barrows'),
('Blake ','null','Crouch'),
('Christina ','Baker ','Kline'),
('Dirk ','null','Cussler'),
('Zadie ','null','Smith'),
('Kristen ','null','Callihan'),
('Jana ','null','Aston'),
('Paul ','null','Beatty'),
('Susan ','null','Wiggs'),
('C ','D ','Reiss'),
('M ','L ','Stedman'),
('Maria ','null','Semple'),
('Carly ','null','Phillips'),
('Carl ','null','Hiaasen'),
('Diane ','null','Chamberlain'),
('William ','Kent ','Krueger'),
('Nathan ','null','Hill'),
('Eva ','null','Natiello'),
('Jasmine ','null','Walt'),
('Emily ','null','Giffin'),
('Noah ','null','Hawley'),
('Laura ','null','Lippman'),
('Raeanne ','null','Thayne'),
('Annie ','null','Proulx'),
('Stephanie ','Dray ','Dray'),
('Laura ','null','Kamoie'),
('Terry ','null','McMillan'),
('Nancy ','null','Thayer'),
('Emma ','null','Straub'),
('Joe ','null','Hill'),
('Stephanie ','null','Danler'),
('Steve ','null','Martini'),
('Steve ','null','Hamilton'),
('Curtis ','null','Sittenfeld'),
('Louise ','null','Erdrich'),
('Shelley ','null','Noble'),
('Rachel ','null','Hauck'),
('Anna ','null','Quindlen'),
('Laurie ','R ','King'),
('Emma ','null','Donoghue'),
('Elena ','null','Ferrante'),
('Fiona ','null','Barton'),
('Audrey ','null','Carlan'),
('Melanie ','null','Benjamin'),
('Michelle ','null','Gable'),
('Sarah ','null','McCoy'),
('Darynda ','null','Jones'),
('Jeanne ','null','Glidewell'),
('James ','null','Hayman'),
('Lauren ','null','Groff'),
('Philip ','K ','Dick'),
('Isabel ','null','Allende'),
('William ','R ','Forstchen'),
('Jessica ','null','Knoll'),
('Leylah ','null','Attar'),
('Cora ','Seton ','Seton'),
('Cherise ','null','Sinclair'),
('Judy ','null','Blume'),
('Anthony ','null','Ryan'),
('Barbara ','null','Delinsky'),
('Gennita ','null','Low'),
('Kate ','null','Atkinson'),
('Helena ','null','Hunting'),
('Toni ','null','Morrison'),
('Jessica ','null','Wood'),
('Sara ','null','Gruen'),
('Donna ','null','Tartt'),
('M ','S ','Force'),
('Anne ','null','Tyler'),
('Peter ','De ','Jonge'),
('Liliana ','null','Hart'),
('Lisa ','null','Genova'),
('Rebecca ','null','Zanetti'),
('Eric ','null','Rickstad'),
('J ','S ','Cooper'),
('Allison ','null','Pataki'),
('Rebecca ','null','Cantrell'),
('J‰ÛäS ','Cooper ','Cooper'),
('Elle ','null','James'),
('Rachel ','null','Joyce'),
('Whitney ','Gracia ','Williams'),
('Jack ','null','Higgins'),
('J ','S ','Scott'),
('Milly ','null','Taiden'),
('Jaci ','null','Burton'),
('Lisa ','Renee ','Jones'),
('Kelley ','R ','Martin'),
('Marilynne ','null','Robinson'),
('Jonathan ','null','Tropper'),
('Victoria ','null','Ashley'),
('Sarah ','null','Waters'),
('Laura ','null','Kaye'),
('Angela ','null','Graham'),
('Opal ','Carew ','Carew'),
('Violet ','null','Duke'),
('edited ',' ','Baldacci'),
('Sue ','Monk ','Kidd'),
('SL ','null','Jennings'),
('Stacy ','null','Borel'),
('Barbara ','null','Kingsolver'),
('JB ','null','Salsbury'),
('Michael ','null','Ponsor'),
('Ted ','null','Bell'),
('Skye ','null','Eagleday'),
('Tawny ','null','Weber'),
('Diane ','null','Capri'),
('J ','Carson ','Black'),
('JS ','Cooper ','Cooper'),
('Mark ','null','Helprin'),
('Orson ','Scott ','Card'),
('Tessa ','null','Bailey'),
('Khaled ','null','Hosseini'),
('Kelly ','null','Elliott'),
('Jack ','Du ','Brul'),
('Nicole ','null','Edwards'),
('Martin ','Cruz ','Smith'),
('Caroline ','null','Leavitt'),
('Wally ','null','Lamb'),
('Helen ','null','Fielding'),
('Elizabeth ','null','Gilbert'),
('Eleanor ','null','Catton'),
('Jhumpa ','null','Lahiri'),
('JD ','Robb ','Robb'),
('Thomas ','null','Perry'),
('A ','S ','Harrison'),
('Elisabeth ','Naughton ','Naughton'),
('Frederick ','null','Forsyth'),
('Irene ','null','Zatko'),
('J ','K ','Rowling'),
('Jeannette ','null','Walls'),
('Lauren ','null','Weisberger'),
('Meg ','Waite ','Clayton'),
('Cassia ','null','Leo'),
('Molly ','null','McAdams'),
('Herman ','null','Koch'),
('Taylor ','null','Stevens'),
('A ','L ','Jackson'),
('Lucy ','null','Kevin'),
('Isaac ','null','Marion'),
('Sister ','null','Souljah'),
('Lorena ','null','McCourtney'),
('Glenn ','Beck ','Beck'),
('Harriet ','null','Parke'),
('Mark ','null','Pearson'),
('Wm ','Paul ','Young'),
('Ayana ','null','Mathis'),
('Cherrie ','null','Lynn'),
('Cora ','null','Carmack'),
('SH ','null','Kolee'),
('Amor ','null','Towles'),
('Katee ','null','Robert'),
('G ','A ','Aiken'),
('Beth ','null','Kerry'),
('Karen ','Thompson ','Walker'),
('Larissa ','null','Ione'),
('Kerrelyn ','null','Sparks'),
('Lisa ','null','Lutz'),
('Richard ','North ','Patterson'),
('Susan ','null','Wilson'),
('Catherine ','null','Bybee'),
('Cindy ','null','Gerard'),
('TÃ©a ','null','Obreht'),
('Elmore ','null','Leonard'),
('Chad ','null','Harbach'),
('Michael ','Crichton ','Crichton'),
('Richard ','null','Preston'),
('Jeffrey ','null','Eugenides'),
('Umberto ','null','Eco'),
('Gregory ','null','Maguire'),
('Chris ','null','Culver'),
('Erin ','null','Morgenstern'),
('Tatiana ','de ','Rosnay'),
('R ','A ','Salvatore'),
('Mary ','null','Blayney'),
('Patricia ','null','Gaffney'),
('Ruth ','Ryan ','Langan'),
('Mary ','Kay ','McComas'),
('Michael ','null','Savage'),
('Beverly ','null','Lewis'),
('David ','null','Nicholls'),
('Michael ','null','Prescott'),
('Tom ','null','Perrotta'),
('Abraham ','null','Verghese'),
('Loretta ','null','Chase'),
('Eric ','Van ','Lustbader'),
('Peter ','null','Telep'),
('J ','Courtney ','Sullivan'),
('Courtney ','null','Milan'),
('Robert ','B ','Parker'),
('Suzanne ','null','Brockmann'),
('Nancy ','C ','Johnson'),
('Sarah ','null','Blake'),
('Chris ','null','Cleave'),
('Michael ','null','Palmer'),
('Charles ','null','Portis')

;
GO

SELECT * FROM  Author
;
GO

INSERT INTO Book
(Book_ISBN,Book_Title,Book_Year,Book_Quantity,Book_Genre)
VALUES
(9781590000000,'THE GIRL ON THE TRAIN',2017,1,26),
(9781590000003,'ALL THE LIGHT WE CANNOT SEE',2017,1,26),
(9781590000005,'ALL THE LIGHT WE CANNOT SEE',2014,1,26),
(9781590000004,'ALL THE LIGHT WE CANNOT SEE',2017,1,26),
(9781590000006,'All Of',2017,1,26),
(9781590000007,'Light',2012,1,26),
(9781590000008,'ALL',2017,1,26),
(9781590030003,'ALL SEE',2017,1,26),
(9781590230003,'THE HANDMAID TALE',2017,1,26),
(9781590040003,'TALE',2017,1,26),
(9781590010003,'HANDMAID',2011,1,26),
(9781593000003,'THE SUN AND',2012,1,26),
(9781590200003,'THE FLOWERS',2013,1,26),
(9781590000043,'THE SUN',2014,1,26),
(9781590005003,'THE SUN AND HER FLOWERSa',2015,1,26),
(9781590060003,'THE SUN AND HER FLOWERSss',2016,1,26),
(9781590700003,'Once',2017,1,26),
(9781590800003,'Upon',2018,1,26),
(9781590900003,'THE SUN AND HER FLOWERS',2019,1,26)


;
GO
SELECT * FROM  Book
;
GO
INSERT INTO Book_Authors
(Book_ISBN,Author_ID)
VALUES
(9781590000000,26),
(9781590000003,22),
(9781590000005,21),
(9781590000004,20),
(9781590000006,19),
(9781590000007,18),
(9781590000008,17),
(9781590030003,25),
(9781590230003,26),
(9781590040003,22),
(9781590010003,17),
(9781593000003,16),
(9781590200003,15),
(9781590000043,14),
(9781590005003,13),
(9781590060003,12),
(9781590700003,10),
(9781590800003,4),
(9781590900003,8)
;
GO

SELECT * FROM  Book_Authors
;
GO